(load 0_Main.clp)
(load 1_Env.clp)
(load ../maps/fleet0.clp)
;;(load 4_Deliberate.clp)
;;(load 5_Planning.clp)
(load 3_Agent.clp)
(load 6_Heat.clp)
(reset)
;(watch focus)
(set-break game-over)
(run)
(run 2)
(focus ENV)
(facts)
