(load 0_Main.clp)
(load 1_Env.clp)
(load ../maps/fleet1.clp)
(load 6_Heat.clp)
(load 8_Convolution.clp)
(load 4_Deliberate.clp)
(load Discover.clp)
(load 5_Planning.clp)
(load 3_Agent.clp)

(reset)
(set-break game-over)
(run)
(run 2)