(load 0_Main.clp)
(load 1_Env.clp)
(load ../maps/fleet0.clp)
(load 2_Heat.clp)
(load 3_Convolution.clp)
(load 4_Deliberate.clp)
(load 5_Discover.clp)
(load 6_Planning.clp)
(load 7_Agent.clp)

(reset)
(set-break game-over)
(run)
